version: '2'
services:
  wuph-notification-sender:
    environment:
      - KAFKA_SERVER=${KAFKA_SERVER}
      - REQUEST_TOPIC=${REQUEST_TOPIC}
      - GROUP_ID=${GROUP_ID}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
    build: .
    hostname: wuph-notification-sender
    container_name: wuph-notification-sender
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  default:
    external: true
    name: weapons-app-network